window.PRODUCTS_DATA = [
  // --- MICROPHONES (5 Items) ---
  {
    id: "mic-demo-1",
    name: "VoiceCraft Studio USB",
    category: "microphones",
    budget: "1000-3000",
    useCases: ["youtube", "podcasting", "streaming"],
    priorities: ["quality", "ease-of-use"],
    features: ["Cardioid Pickup Pattern", "Zero-Latency Monitoring", "Built-in Pop Filter"],
    description: "Plug-and-play USB microphone ideal for crystal clear speech and vocal recording.",
    pros: ["Easy USB setup", "Natural voice response"],
    cons: ["Included desk stand absorbs desk bumps"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-2",
    name: "StreamBeast XLR Dynamic",
    category: "microphones",
    budget: "5000-10000",
    useCases: ["podcasting", "streaming", "gaming"],
    priorities: ["quality", "features"],
    features: ["XLR Broadcast Connection", "Dynamic Capsule", "Off-axis Noise Rejection"],
    description: "Broadcast-grade dynamic microphone designed for noisy room environments.",
    pros: ["Exceptional background noise rejection", "Durable metal chassis"],
    cons: ["Requires audio interface or preamp"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-3",
    name: "EchoBud Mini USB",
    category: "microphones",
    budget: "under-1000",
    useCases: ["online-classes", "gaming"],
    priorities: ["price", "portability"],
    features: ["Compact Footprint", "Quick Mute Button", "Flexible Gooseneck"],
    description: "Ultra-budget desk microphone perfect for daily online classes and quick calls.",
    pros: ["Very affordable", "Extremely portable"],
    cons: ["Basic frequency range"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-4",
    name: "PodcastPro Condenser",
    category: "microphones",
    budget: "3000-5000",
    useCases: ["podcasting", "youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Dual Pickup Patterns", "Gain Control Knob", "Shock Mount Included"],
    description: "Versatile studio condenser microphone for multi-person interviews and podcasts.",
    pros: ["High sensitivity", "Multiple polar patterns"],
    cons: ["Picks up room echo easily"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-5",
    name: "MasterVoice Ultra Broadcast",
    category: "microphones",
    budget: "10000+",
    useCases: ["youtube", "podcasting", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Premium Capsule", "Internal Shock Isolation", "Built-in DSP EQ"],
    description: "Flagship recording microphone providing radio-grade acoustic performance.",
    pros: ["Studio-grade clarity", "Built-in hardware DSP"],
    cons: ["Higher investment cost"],
    badge: "Demo",
    retailerUrl: "#"
  },

  // --- WEBCAMS (5 Items) ---
  {
    id: "cam-demo-1",
    name: "ClearView 1080p HD",
    category: "webcams",
    budget: "1000-3000",
    useCases: ["online-classes", "youtube", "content-creation"],
    priorities: ["ease-of-use", "price"],
    features: ["Full HD 1080p 30fps", "Privacy Shutter", "Dual Stereo Microphones"],
    description: "Reliable, high-definition camera with auto-exposure for sharp video conferencing.",
    pros: ["Great automatic light adjustment", "Physical privacy shutter"],
    cons: ["Fixed focal length"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-2",
    name: "StreamPro 4K Ultra",
    category: "webcams",
    budget: "10000+",
    useCases: ["streaming", "youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Native 4K HDR", "AI Auto-Framing", "60 FPS at 1080p"],
    description: "Flagship webcam offering broadcast-quality video capture with advanced controls.",
    pros: ["Unmatched image clarity", "Smooth 60 FPS option"],
    cons: ["Requires high-speed USB 3.0 port"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-3",
    name: "ClassCam 720p Lite",
    category: "webcams",
    budget: "under-1000",
    useCases: ["online-classes", "gaming"],
    priorities: ["price", "portability"],
    features: ["720p HD Video", "Clip Mount", "Plug and Play"],
    description: "Budget-friendly camera setup for casual video calls and remote schooling.",
    pros: ["Plug & play simplicity", "Extremely low cost"],
    cons: ["Lower resolution in dim rooms"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-4",
    name: "FocusCam 60FPS Pro",
    category: "webcams",
    budget: "3000-5000",
    useCases: ["gaming", "streaming"],
    priorities: ["quality", "ease-of-use"],
    features: ["1080p 60FPS", "Fast Auto-Focus", "Tripod Mount Thread"],
    description: "Smooth high-frame-rate webcam tailored for action gaming streamers.",
    pros: ["Fluid 60fps video", "Fast autofocus speed"],
    cons: ["Colors require slight manual tweaking"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-5",
    name: "LumiCam Studio Glow",
    category: "webcams",
    budget: "5000-10000",
    useCases: ["streaming", "content-creation"],
    priorities: ["features", "quality"],
    features: ["Integrated Ring Light", "Wide Angle Lens", "Custom Software Control"],
    description: "All-in-one web camera equipped with built-in LED lighting ring.",
    pros: ["Built-in lighting", "Wide field of view"],
    cons: ["Slightly bulkier design"],
    badge: "Demo",
    retailerUrl: "#"
  },

  // --- TRIPODS (5 Items) ---
  {
    id: "tri-demo-1",
    name: "FlexiLeg Gorilla Grip",
    category: "tripods",
    budget: "under-1000",
    useCases: ["content-creation", "youtube"],
    priorities: ["portability", "ease-of-use"],
    features: ["Flexible Rubber Legs", "Universal Phone Clamp", "Bluetooth Shutter"],
    description: "Versatile, flexible mini-tripod that wraps around objects for creative angles.",
    pros: ["Mounts anywhere", "Very lightweight"],
    cons: ["Not designed for heavy DSLRs"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-2",
    name: "StudioTower Heavy Duty",
    category: "tripods",
    budget: "3000-5000",
    useCases: ["youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Aluminum Alloy Frame", "Fluid Pan Head", "Quick-Release Plate"],
    description: "Sturdy full-height tripod providing silky smooth panning for video setups.",
    pros: ["High pan/tilt stability", "Extends to 65 inches"],
    cons: ["Heavy for backpack travel"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-3",
    name: "CompactPocket Desk Stand",
    category: "tripods",
    budget: "1000-3000",
    useCases: ["online-classes", "gaming"],
    priorities: ["price", "portability"],
    features: ["Tabletop Design", "360-degree Ballhead", "Folds Flat"],
    description: "Minimalist desktop tripod for webcams, smartphones, and small lights.",
    pros: ["Takes zero desk space", "Sturdy ball joint"],
    cons: ["Limited vertical height"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-4",
    name: "TravelLite Carbon Tripod",
    category: "tripods",
    budget: "5000-10000",
    useCases: ["youtube", "content-creation"],
    priorities: ["portability", "quality"],
    features: ["Carbon Fiber Tubes", "Compact Fold-back", "Monopod Conversion"],
    description: "Ultra-lightweight travel tripod built for outdoor and mobile creators.",
    pros: ["Extremely light carbon construction", "Monopod mode"],
    cons: ["Higher price tag"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-5",
    name: "ProRig Overhead Rig Mount",
    category: "tripods",
    budget: "10000+",
    useCases: ["content-creation", "youtube"],
    priorities: ["features", "quality"],
    features: ["Overhead Extension Arm", "Multi-Mount Clamps", "Heavy Payload Capacity"],
    description: "Specialized overhead desk rig for unboxing videos and desktop tutorials.",
    pros: ["Perfect 90-degree overhead shots", "Holds heavy gear"],
    cons: ["Requires sturdy desk edge for clamping"],
    badge: "Demo",
    retailerUrl: "#"
  },

  // --- RING LIGHTS (5 Items) ---
  {
    id: "ring-demo-1",
    name: "GlowPro 10-inch Desktop",
    category: "ring-lights",
    budget: "1000-3000",
    useCases: ["streaming", "online-classes", "content-creation"],
    priorities: ["price", "ease-of-use"],
    features: ["3 Color Modes", "USB Powered", "In-line Controller"],
    description: "Compact lighting setup providing even illumination for video calls.",
    pros: ["Easy inline dimming", "Standard USB power"],
    cons: ["Desk-only height range"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "ring-demo-2",
    name: "AuraMax 18-inch Studio Light",
    category: "ring-lights",
    budget: "5000-10000",
    useCases: ["youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Bi-Color Temperature (3200K-5600K)", "AC Power Adapter", "Wireless Remote"],
    description: "Large professional ring light offering bright, soft facial illumination.",
    pros: ["Broad lighting coverage", "Stepless brightness control"],
    cons: ["Requires dedicated floor space"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "ring-demo-3",
    name: "MiniClip Phone Glow",
    category: "ring-lights",
    budget: "under-1000",
    useCases: ["online-classes", "content-creation"],
    priorities: ["price", "portability"],
    features: ["Clip-on Design", "Rechargeable Battery", "Pocket Sized"],
    description: "Small clip-on ring light designed for smartphones and laptops.",
    pros: ["Fits in pocket", "Ultra-cheap solution"],
    cons: ["Short battery duration on max boost"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "ring-demo-4",
    name: "LightPanel Key Glow",
    category: "ring-lights",
    budget: "3000-5000",
    useCases: ["streaming", "gaming"],
    priorities: ["features", "ease-of-use"],
    features: ["Desk Edge Clamp", "Soft Diffuser Panel", "App Control Option"],
    description: "Non-glare streaming panel light designed to protect eyes during long sessions.",
    pros: ["Zero eye strain", "Space-saving desk clamp"],
    cons: ["Does not produce ring light eye reflections"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "ring-demo-5",
    name: "StudioHalo Dual Ring Rig",
    category: "ring-lights",
    budget: "10000+",
    useCases: ["content-creation", "youtube"],
    priorities: ["quality", "features"],
    features: ["Dual Light Heads", "High CRI 95+", "Heavy Studio Stand"],
    description: "Premium twin-light setup eliminating shadows completely for macro beauty recording.",
    pros: ["Professional High CRI color rendering", "Zero shadows"],
    cons: ["Complex setup space requirements"],
    badge: "Demo",
    retailerUrl: "#"
  },

  // --- HEADPHONES (5 Items) ---
  {
    id: "head-demo-1",
    name: "AudioAcoustic Monitor 50",
    category: "headphones",
    budget: "3000-5000",
    useCases: ["podcasting", "gaming", "youtube"],
    priorities: ["quality", "features"],
    features: ["Closed-Back Design", "50mm Neodymium Drivers", "Padded Ear Cushions"],
    description: "Over-ear studio monitoring headphones tailored for clear audio editing.",
    pros: ["Flat neutral sound profile", "Great sound isolation"],
    cons: ["Non-detachable audio cable"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "head-demo-2",
    name: "StreamBuds Wireless Pro",
    category: "headphones",
    budget: "5000-10000",
    useCases: ["gaming", "streaming"],
    priorities: ["ease-of-use", "portability"],
    features: ["Low-Latency Wireless", "Detachable Boom Mic", "24-Hour Battery"],
    description: "Lag-free wireless headset built for gaming and long live-streaming sessions.",
    pros: ["Zero wire clutter", "Very comfortable earcups"],
    cons: ["Requires USB wireless dongle"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "head-demo-3",
    name: "BasicEar Earbuds Lite",
    category: "headphones",
    budget: "under-1000",
    useCases: ["online-classes", "gaming"],
    priorities: ["price", "portability"],
    features: ["3.5mm Jack", "In-line Microphone", "Tangle-Free Cable"],
    description: "Budget in-ear earphones for basic listening, video lectures, and voice calls.",
    pros: ["Ultra affordable", "Pocketsize convenience"],
    cons: ["Minimal bass response"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "head-demo-4",
    name: "ComfortHead Studio 20",
    category: "headphones",
    budget: "1000-3000",
    useCases: ["podcasting", "online-classes"],
    priorities: ["price", "ease-of-use"],
    features: ["Lightweight Headband", "Velour Ear Pads", "Swivel Earcups"],
    description: "Comfort-focused over-ear headphones built for hours of editing without fatigue.",
    pros: ["Lightweight feel", "Breathable ear pads"],
    cons: ["Passive noise blocking is moderate"],
    badge: "Demo",
    retailerUrl: "#"
  },
  {
    id: "head-demo-5",
    name: "ReferenceCraft Pro 100",
    category: "headphones",
    budget: "10000+",
    useCases: ["podcasting", "youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Open-Back Reference Design", "Planar Magnetic Tech", "Braided Cable"],
    description: "Audiophile-grade open-back headphones for master sound mixing and audio production.",
    pros: ["Unrivaled soundstage width", "Precision detail retrieval"],
    cons: ["Sound leaks out (open-back design)"],
    badge: "Demo",
    retailerUrl: "#"
  }
];
