window.PRODUCTS_DATA = [
  {
    id: "mic-demo-1",
    name: "VoiceCraft Studio USB",
    category: "microphones",
    budgets: ["1000-3000", "3000-5000"],
    useCases: ["youtube", "podcasting", "streaming"],
    priorities: ["quality", "ease-of-use"],
    features: ["Cardioid Pickup Pattern", "Zero-Latency Monitoring", "Built-in Pop Filter"],
    description: "Plug-and-play USB microphone ideal for crystal clear speech and vocal recording.",
    badge: "Best Match",
    pros: "Easy setup, natural voice response",
    cons: "Desk stand absorbs vibration",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-2",
    name: "StreamBeast XLR Dynamic",
    category: "microphones",
    budgets: ["5000-10000", "10000+"],
    useCases: ["podcasting", "streaming", "gaming"],
    priorities: ["quality", "features"],
    features: ["XLR Broadcast Connection", "Dynamic Capsule", "Off-axis Noise Rejection"],
    description: "Broadcast-grade dynamic microphone designed for noisy room environments.",
    badge: "Pro Pick",
    pros: "Exceptional room noise isolation",
    cons: "Requires audio interface or mixer",
    retailerUrl: "#"
  },
  {
    id: "mic-demo-3",
    name: "EchoBud Mini USB",
    category: "microphones",
    budgets: ["under-1000"],
    useCases: ["online-classes", "gaming"],
    priorities: ["price", "portability"],
    features: ["Compact Design", "Mute Button", "Flexible Gooseneck"],
    description: "Ultra-budget desk microphone perfect for daily online classes and quick calls.",
    badge: "Budget Choice",
    pros: "Very affordable, extremely compact",
    cons: "Basic audio fidelity",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-1",
    name: "ClearView 1080p HD",
    category: "webcams",
    budgets: ["1000-3000", "3000-5000"],
    useCases: ["online-classes", "youtube", "content-creation"],
    priorities: ["ease-of-use", "price"],
    features: ["Full HD 1080p 30fps", "Privacy Shutter", "Dual Stereo Microphones"],
    description: "Reliable, high-definition camera with auto-exposure for sharp video conferencing.",
    badge: "Top Seller",
    pros: "Great low-light adjustment",
    cons: "Fixed focal distance",
    retailerUrl: "#"
  },
  {
    id: "cam-demo-2",
    name: "StreamPro 4K Ultra",
    category: "webcams",
    budgets: ["10000+"],
    useCases: ["streaming", "youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Native 4K HDR", "AI Auto-Framing", "60 FPS at 1080p"],
    description: "Flagship webcam offering broadcast-quality video capture with advanced exposure controls.",
    badge: "Premium",
    pros: "Unmatched clarity and color balance",
    cons: "Requires USB 3.0 port",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-1",
    name: "FlexiLeg Gorilla Grip",
    category: "tripods",
    budgets: ["under-1000", "1000-3000"],
    useCases: ["content-creation", "youtube"],
    priorities: ["portability", "ease-of-use"],
    features: ["Flexible Joints", "Universal Phone Mount", "Bluetooth Remote"],
    description: "Versatile, flexible mini-tripod that wraps around objects for creative camera angles.",
    badge: "Versatile",
    pros: "Attaches anywhere, lightweight",
    cons: "Not suitable for heavy DSLR cameras",
    retailerUrl: "#"
  },
  {
    id: "tri-demo-2",
    name: "StudioTower Heavy Duty",
    category: "tripods",
    budgets: ["3000-5000", "5000-10000"],
    useCases: ["youtube", "content-creation"],
    priorities: ["quality", "features"],
    features: ["Aluminum Alloy Legs", "Fluid Pan Head", "Quick-Release Plate"],
    description: "Sturdy full-height tripod providing silky smooth panning for professional video setups.",
    badge: "Solid Pick",
    pros: "Stable, fluid head movements",
    cons: "Heavier to carry around",
    retailerUrl: "#"
  },
  {
    id: "ring-demo-1",
    name: "GlowPro 10-inch Desktop",
    category: "ring-lights",
    budgets: ["1000-3000"],
    useCases: ["streaming", "online-classes", "content-creation"],
    priorities: ["price", "ease-of-use"],
    features: ["3 Color Modes", "USB Powered", "In-line Remote Control"],
    description: "Compact lighting setup providing even illumination for video calls and content creators.",
    badge: "Popular",
    pros: "Easy dimming, powered by standard USB",
    cons: "Desktop height limit",
    retailerUrl: "#"
  },
  {
    id: "head-demo-1",
    name: "AudioAcoustic Monitor 50",
    category: "headphones",
    budgets: ["3000-5000", "5000-10000"],
    useCases: ["podcasting", "gaming", "youtube"],
    priorities: ["quality", "features"],
    features: ["Closed-Back Acoustic Design", "50mm Neodymium Drivers", "Padded Ear Cushions"],
    description: "Over-ear studio monitoring headphones tailored for clear audio editing and critical listening.",
    badge: "Audio Pick",
    pros: "Flat neutral frequency response",
    cons: "Non-detachable cable",
    retailerUrl: "#"
  }
];

